"""Add puntuacion

Revision ID: 0ef542edfd20
Revises: 4947f6240b3a
Create Date: 2026-03-18 19:50:08.068756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef542edfd20'
down_revision: Union[str, Sequence[str], None] = '4947f6240b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patinetes', sa.Column('puntuacion_usuario', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patinetes', 'puntuacion_usuario')
    # ### end Alembic commands ###
